### PR TITLE
I have done the logo

### PR DESCRIPTION
**Pull request by aureliosss**

### CODE REVIEW

**Comment by aureliosss** [comment]
I changed!

**Comment by Dariusionut** [comment]
Pull request name should contain the ticket name. You can add additional details in the description section

**Comment by Dariusionut** [comment]
static must me a directory inside the the resources folder. 
It is already existent.
bug

**Comment by aureliosss** [comment]
Updated application logo image
logo_updated

**Comment by Dariusionut** [comment]
Images should be inside static folder and not inside static/scripts.
The file should be name logo.png

**Review by Dariusionut — APPROVED** [review]

**Pull request merged**
